version: '3.7'

services: 
  database:
    image: postgres
    container_name: library_database
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=library02
      - POSTGRES_DB=library
    volumes: 
      - pgdata:/data/postgres
  
  api:
    build: .
    container_name: api_library
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/libraryapi
    links: 
      - database
    depends_on: 
      - database

volumes: 
  pgdata:
    driver: local